/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : MainMotor.h
**     Project     : ProcessorExpert
**     Processor   : MKL25Z128VLK4
**     Component   : PPG
**     Version     : Component 02.195, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-05-26, 09:40, # CodeGen: 70
**     Abstract    :
**         This component "PPG" implements a programmable
**         pulse generator that generates signal with variable
**         duty and variable cycle (period).
**     Settings    :
**         Used output pin             : 
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       43            |  ADC0_SE8/TSI0_CH0/PTB0/LLWU_P5/I2C0_SCL/TPM1_CH0
**             ----------------------------------------------------
**
**         Timer name                  : TPM1_CNT [16-bit]
**         Counter                     : TPM1_CNT  [0x40039004]
**         Mode register               : TPM1_SC   [0x40039000]
**         Run register                : TPM1_SC   [0x40039000]
**         Prescaler                   : TPM1_SC   [0x40039000]
**         Compare 1 register          : TPM1_MOD  [0x40039008]
**         Compare 2 register          : TPM1_C0V  [0x40039010]
**         Flip-flop 1 register        : TPM1_SC   [0x40039000]
**         Flip-flop 2 register        : TPM1_C0SC [0x4003900C]
**
**         User handling procedure     : not specified
**
**         Output pin
**
**         Port name                   : PTB
**         Bit number (in port)        : 0
**         Bit mask of the port        : 0x0001
**         Port data register          : GPIOB_PDOR [0x400FF040]
**         Port control register       : GPIOB_PDDR [0x400FF054]
**
**         Runtime setting period      : modes (list of settings)
**         Runtime setting ratio       : calculated
**         Initialization:
**              Output level           : low
**              Timer                  : Enabled
**              Event                  : Enabled
**         High speed mode
**             Prescaler               : divide-by-16
**           Initial value of            period        pulse width (ratio 5%)
**             microseconds            : 20000         1000
**             milliseconds            : 20            1
**             seconds (real)          : 0.02          0.001
**
**     Contents    :
**         SetPeriodMode - byte MainMotor_SetPeriodMode(byte Mode);
**         SetRatio16    - byte MainMotor_SetRatio16(word Ratio);
**         SetDutyUS     - byte MainMotor_SetDutyUS(word Time);
**         SetDutyMS     - byte MainMotor_SetDutyMS(word Time);
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file MainMotor.h
** @version 01.00
** @brief
**         This component "PPG" implements a programmable
**         pulse generator that generates signal with variable
**         duty and variable cycle (period).
*/         
/*!
**  @addtogroup MainMotor_module MainMotor module documentation
**  @{
*/         

#ifndef __MainMotor_H
#define __MainMotor_H

/* MODULE MainMotor. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "PpgLdd1.h"

#include "Cpu.h"


#define MainMotor_PERIOD_VALUE PpgLdd1_PERIOD_TICKS /* Initial period value in ticks of the timer. It is available only if the bean is enabled in high speed mode. */
#define MainMotor_PERIOD_VALUE_HIGH PpgLdd1_PERIOD_TICKS_0 /* Period value in ticks of the timer in high speed mode. It is available only if the bean is enabled in high speed mode. */
/* These constants may be used as a parameter for SetPeriodMode method, value is an index of selected user mode.  */
#define MainMotor_PM_50Hz  PpgLdd1_SP_50Hz /* Constant for switch to mode 0 */
#define MainMotor_PM_6Hz   PpgLdd1_SP_6Hz /* Constant for switch to mode 1 */
#define MainMotor_PM_12Hz  PpgLdd1_SP_12Hz /* Constant for switch to mode 2 */
#define MainMotor_PM_15Hz  PpgLdd1_SP_15Hz /* Constant for switch to mode 3 */
#define MainMotor_PM_18Hz  PpgLdd1_SP_18Hz /* Constant for switch to mode 4 */
#define MainMotor_PM_21Hz  PpgLdd1_SP_21Hz /* Constant for switch to mode 5 */
#define MainMotor_PM_24Hz  PpgLdd1_SP_24Hz /* Constant for switch to mode 6 */
#define MainMotor_PM_27Hz  PpgLdd1_SP_27Hz /* Constant for switch to mode 7 */
#define MainMotor_PM_30Hz  PpgLdd1_SP_30Hz /* Constant for switch to mode 8 */



/*
** ===================================================================
**     Method      :  MainMotor_SetPeriodMode (component PPG)
**     Description :
**         This method switches the component to a specified mode
**         (changes the period/frequency using the mode values). Each
**         mode is identified by a single 8-bit unsigned number which
**         expresses one period/frequency of the generated signal. This
**         method reduce the time needed for setting a new period value.
**         This method is enabled only if a list of possible period
**         settings is specified at design time (see <Timing dialog box>
**         - Runtime setting - from a list of values). Each of these
**         settings constitutes a _/mode/_ and Processor Expert assigns
**         them a _/mode identifier/_ (see public constants in the
**         generated header file). The prescaler and compare values
**         corresponding to each mode are calculated at design time.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Mode            - Specifies a Mode to switch to. It is
**                           recommended to use public constants from
**                           the generated header file.
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_VALUE - Value out of range, the
**                           requested timing mode is not defined
** ===================================================================
*/
byte MainMotor_SetPeriodMode(byte Mode);

/*
** ===================================================================
**     Method      :  MainMotor_SetRatio16 (component PPG)
**     Description :
**         This method sets a new duty-cycle ratio. Ratio is expressed
**         as a 16-bit unsigned integer number. Value 0 - 65535 value
**         is proportional to ratio 0 - 100%. 
**         Note: Calculated duty depends on the timer possibilities and
**         on the selected period.
**         The method is available only if method <SetPeriodMode> is
**         not selected.
**     Parameters  :
**         NAME            - DESCRIPTION
**         Ratio           - Ratio to set. 0 - 65535 value is
**                           proportional to ratio 0 - 100%
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
** ===================================================================
*/
#define MainMotor_SetRatio16(Ratio) (PpgLdd1_SetRatio16(PpgLdd1_DeviceData, Ratio))

/*
** ===================================================================
**     Method      :  MainMotor_SetDutyUS (component PPG)
**     Description :
**         This method sets the new duty value of the output signal. The
**         duty is expressed in microseconds as a 16-bit unsigned integer
**         number.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Time       - Duty to set [in microseconds]
**     Returns     :
**         ---        - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_MATH - Overflow during evaluation
**                           ERR_RANGE - Parameter out of range
** ===================================================================
*/
byte MainMotor_SetDutyUS(word Time);

/*
** ===================================================================
**     Method      :  MainMotor_SetDutyMS (component PPG)
**     Description :
**         This method sets the new duty value of the output signal. The
**         duty is expressed in milliseconds as a 16-bit unsigned integer
**         number.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Time       - Duty to set [in milliseconds]
**     Returns     :
**         ---        - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - This device does not work in
**                           the active speed mode
**                           ERR_MATH - Overflow during evaluation
**                           ERR_RANGE - Parameter out of range
** ===================================================================
*/
byte MainMotor_SetDutyMS(word Time);

/* END MainMotor. */

#endif 
/* ifndef __MainMotor_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
